XRAY_PLUGIN = "JIRA_XRAY"
XRAY_MARKER_NAME = "xray"
XRAY_API_BASE_URL_DEFAULT = "https://xray.example.com/rest/"
XRAY_EVIDENCE = "xray_evidence"
XRAY_RESULT = "xray_result"
JIRA_XRAY_FLAG = "--jira-xray"
XRAY_TEST_EXEC_ARG = "--jira-xray-test-exec-key"
